import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import CartLogin from "@/components/CartLogin";
import Hamburger from "@/components/Hamburger";
import { UserProvider } from "@/components/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ultra Shop",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <CartLogin/>
          <Hamburger/>
          <NavBar/>
          {children}
          <Footer/>
        </UserProvider>
      </body>
    </html>
  );
}
